on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - 'canary*'

jobs:
  test:
    container:
      image: node:alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm test:run
  build:
    container:
      image: node:alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm build

  